# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
#  - name: News
#    url: 'news/newslist'
#    weight: 20
  - name: Group
    url: '/group/'
    weight: 30
  - name: Publications
    url: '/publication'
    weight: 30
  - name: Courses
    url: '/course/'
    weight: 50
#  - name: Services
#    url: '/service/servicelist'
#    weight: 60
  - name: Talks
    url: '/talk/'
    weight: 70
#  - name: Awards
#    url: '/award/awardlist'
#    weight: 80
  - name: Contact
    url: '#contact'
    weight: 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: CV
    url: uploads/resume.pdf
    weight: 100