name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch from which you want to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (if you're using a submodule)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.116.0'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Create CNAME
      run: echo "ali-emami.com" > public/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./public
